# Generated by Django 4.1.7 on 2023-03-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
