# Generated by Django 4.1.7 on 2023-03-18 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.member'),
        ),
    ]
