# Generated by Django 4.1.7 on 2023-03-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_servicerequest_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='member',
        ),
    ]
