# Generated by Django 4.1.7 on 2023-03-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='messages',
            new_name='message',
        ),
    ]
