# Generated by Django 4.1.7 on 2023-03-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_messages_messages_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectioncenter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='collectioncompany',
            name='id',
        ),
        migrations.AddField(
            model_name='collectioncenter',
            name='center_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collectioncompany',
            name='company_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
