# Generated by Django 4.1.7 on 2023-03-24 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='text',
        ),
    ]
