# Generated by Django 4.1.7 on 2023-03-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_message_feedback_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.member'),
        ),
        migrations.AlterField(
            model_name='report',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.member'),
        ),
    ]
