# Generated by Django 4.1.7 on 2023-03-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_delete_messages_alter_feedback_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
