# Generated by Django 4.1.7 on 2023-03-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_feedback_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
    ]
