# Generated by Django 4.1.7 on 2023-04-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_member_email_remove_member_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='id',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='report_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
