# Generated by Django 4.1.7 on 2023-04-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_servicerequest_id_servicerequest_report_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='report_id',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
